api = "0.4"

[buildpack]
id = "dajulia3/apt"
version = "0.1.0"
name = "apt Packages Buildpack"
homepage = "https://github.com/fagiani/apt-buildpack"
description = "Installs apt packages for further builds and runtime with support for bionic stack. Forked from fagiani/apt."
keywords = ["apt", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
